Error: Resolved Error: fixed assets image path name (#36)
* Merge: Project setup (#2)

* config: setup the project envirnomonet

* config: installed scss and react-router-dom

* config: implement router using the react-router-dom

* config: applied scss formatted files

* config: implement prettier and eslint

- inspected installed packages, implemented configuration , everything is okay.

* config: add `.env` to the `.gitignore` file

* config: create main components and implement them in the `App.tsx`

* config: implement path alias

* Merge: Implement the Design System - fonts (#4)

* config: setup the project envirnomonet

* config: installed scss and react-router-dom

* config: implement router using the react-router-dom

* config: applied scss formatted files

* config: implement prettier and eslint

- inspected installed packages, implemented configuration , everything is okay.

* config: add `.env` to the `.gitignore` file

* config: create main components and implement them in the `App.tsx`

* config: implement path alias

* config: implement thirdwebjs

* config: implement design system fonts

* config: update design system fonts

* feat: implement design fonts system in the scss files

- using the `@mixin`, `@include`

* Merge: Implement media-query (#6)

* feat: chaned `@import` to `@use`

* feat: implement mediaQuery

* feat: create Show components and implemented designsystem

* feat: checked mediaquery and code structure

* Merge: Create UI Elements (#8)

* feat: chaned `@import` to `@use`

* feat: implement mediaQuery

* feat: create Show components and implemented designsystem

* feat: checked mediaquery and code structure

* feat: create AboutFrame Elements UI

* feat: create TokenFrame Elements UI

* feat: create Tokenomics components

* feat: create footer and header components

* feat: edited design system to update margin& padding

* 🔀: Create UI layout component  (#10)

* feat: create BaseLayout components

* feat: create MarginLayout components

* feat: create Slider Model Components

* feat: split Layout Components and apply new Layout Components

* feat: create Error styled scss for the props checked

* feat: remove unused files

* feat: add description to how to use this components

* feat: remaned Slider to SliderFlex

- SliderFlex edited to be possible and dynamically changed based on the prop type

* feat: applied the SliderFlex components in each other's files

* feat: SliderFlex test

* feat: SliderFlex components revert to prevent task code.

* feat: implement screen aspect ratio tracking using useEffect

* config: add color system to the design system

* feat: edited comments

* Merge: Implement specific functionality (#14)

* feat: installed react-slick and slick-carousel

* feat: implemented Slider components reference to the `feature/11-test-slider`.

* feat: create custom Hook for tracking window size.

* feat: create a custom slick scss file and apply it to the slider area.

* feat: added parameter in the `useTrackingView`

* feat: apply `useTrackingView` each required files.

* feat: "Adjust the slider to fit the display size.

* Merge: Create RoadMap UI (#16)

* feat: installed react-slick and slick-carousel

* feat: implemented Slider components reference to the `feature/11-test-slider`.

* feat: create custom Hook for tracking window size.

* feat: create a custom slick scss file and apply it to the slider area.

* feat: added parameter in the `useTrackingView`

* feat: apply `useTrackingView` each required files.

* feat: "Adjust the slider to fit the display size.

* feat: create RoadMapFrame UI element.

* Merge : Implement specific functionality for RoadMap (#17)

* feat: created RoadMap Components and applied in the Main Components.

* feat: implement slider effect

- if hover on the effectRef element, don't scrolling. need inspect about it.

* feat: implement sencer in the effect div to detect scrolling

* Merge: Create Train UI and implement infinity scrolling functionality (#19)

* feat: remove to unused comments

* feat: Create Train UI and implement infinity scrolling functionality

- need inspect `infinitySlider` and `TrainFrame`

* feat: inspected `InfinitySlider.tsx` and updated that components, fixed scss

* Merge: Create SNS UI (#21)

* feat: refactored to `RoadMap.tsx` to adjust margins for a dispaly purposes.

* feat: split env procution mode and development mode

* feat: create Error components and implements

* feat: show page insert image

* feat: create SNS UI

* Merge : Create Data Base, format is JSON (#23)

* feat: Create SNS Data Json

* feat: Record Type updated `string` to `number`.

* feat: rename assets/img files

* feat: insert About image

* feat: implement picture, source tag for optimization

* feat: `useTrackingView` replace with `picture/source` tag in the SNS components.

* feat: Create About Data Json

* feat: update sns, about.json files and changed to maping key name.

* feat: Create Tokenomics Data Json

* feat: update Show components.

* feat: checked the show components to find problem

- need inspect and refactoring the show components

* feat: fixed show layout.

* feat: fixed details elements of the margin, height, width.

* feat: fixed details elements of the margin, height, width.

* feat: fixed the TokenFrame, Tokenomics components details elements of the margin, height, width.

* feat: Create roadMap Data Json

* feat: fixed sns, snsFrame, tokenFram.

* feat: fixed snsFrame.

* Merge : implement the 'About' elements to display the description. (#25)

* Merge: Create WhitePaper UI (#27)

* feat: implement the 'About' elements to display the description.

* feat: create white paper UI

* Merge: Create Univers UI (#29)

* Merge: Inspect main page (#31)

* feat: set up the margin of the margin

* feat: implemented font size and margin

* feat: implement to translate functionality.

* feat: installed `@types/node`

* feat: fixed assets image path name.

* feat: fixed assets image path name.

* feat: fixed assets image path name.